version: "3"

services:

  vote:
    labels:
      shipyard.route: '/vote'
      shipyard.route.rewrite: true
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    labels:
      shipyard.route: '/result'
      shipyard.route.rewrite: true
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    ports:
      - 5432

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
